name: ARM Template Build and Test

on: [ push, pull_request ]

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Run Bicep build
      uses: aliencube/bicep-build-actions@v0.1
      with:
        files: '**/*.bicep'

    - name: Run the private action - path
      id: pathtest
      uses: ./
      with:
        path: ./resources

    - name: Test result (bash) - path
      shell: bash
      continue-on-error: true
      run: |
        echo "${{ toJSON(fromJSON(steps.pathtest.outputs.results)) }}"

    - name: Test result (powershell) - path
      shell: pwsh
      continue-on-error: true
      run: |
        ${{ toJSON(steps.pathtest.outputs.results) }} | ConvertFrom-Json | ConvertTo-Json

    - name: Run the private action - files
      id: filestest
      uses: ./
      with:
        path: ./resources
        files: sample.json

    # - name: Test result - files
    #   shell: bash
    #   continue-on-error: true
    #   run: |
    #     echo ${{ steps.filestest.outputs.results }}
    #     echo "Results $results"

    - name: Run the private action - specify tests
      id: teststest
      uses: ./
      with:
        path: ./resources
        tests: '"apiVersions Should Be Recent","Resources Should Have Location"'

    # - name: Test result - specify tests
    #   shell: bash
    #   continue-on-error: true
    #   run: |
    #     results=${{ steps.teststest.outputs.results }}
    #     echo "Results $results"

    - name: Run the private action - skip tests
      id: skipstest
      uses: ./
      with:
        path: ./resources
        skips: '"apiVersions Should Be Recent","Resources Should Have Location"'

    # - name: Test result - skp tests
    #   shell: bash
    #   continue-on-error: true
    #   run: |
    #     echo ${{ steps.skipstest.outputs.results }}
    #     echo "Results $results"
