name: ARM Template Build and Test

on: push

jobs:
  build_and_test:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Run Bicep build
      uses: aliencube/bicep-build-actions@v0.1
      with:
        files: '**/*.bicep'

    - name: Run the private action - path
      id: pathtest
      uses: ./
      with:
        path: ./sample.json

    - name: Test result - path
      shell: bash
      run: |
        results=${{ steps.pathtest.outputs.results }}
        results="${results//'\\E[35m'/''}"
        # results="${results//$'\n'/'%0A'}"
        # results="${results//$'\r'/'%0D'}"
        echo "Results $results"

    - name: Run the private action - files
      id: filestest
      uses: ./
      with:
        path: ./
        files: sample.json

    - name: Test result - files
      shell: bash
      run: |
        echo ${{ steps.filestest.outputs.results }}
        # results="${results//$'%'/'%25'}"
        # results="${results//$'\n'/'%0A'}"
        # results="${results//$'\r'/'%0D'}"
        # echo "Results $results"

    - name: Run the private action - specify tests
      id: teststest
      uses: ./
      with:
        path: ./
        files: sample.json
        tests: apiVersions

    - name: Test result - files
      shell: bash
      run: |
        results=${{ steps.teststest.outputs.results }}
        # results="${results//$'%'/'%25'}"
        # results="${results//$'\n'/'%0A'}"
        # results="${results//$'\r'/'%0D'}"
        # echo "Results $results"

    - name: Run the private action - skip tests
      id: skipstest
      uses: ./
      with:
        path: ./
        files: sample.json
        skips: apiVersions

    - name: Test result - files
      shell: bash
      run: |
        echo ${{ steps.skipstest.outputs.results }}
        # results="${results//$'%'/'%25'}"
        # results="${results//$'\n'/'%0A'}"
        # results="${results//$'\r'/'%0D'}"
        # echo "Results $results"
